### ISSUE TITLE
Standardized build config

### ISSUE THREAD

**Issue by bendmorris** [HaxeFoundation/haxe-evolution#43]
Moved from https://github.com/HaxeFoundation/haxe-evolution/issues/42

I agree with the goal but we're bumping up against the limits of what a format like hxml should reasonably support (hierarchical structure?) There's a natural split between compiler args and build configuration: build config should be flexible and expressive, and generates a set of compiler args for a single build, which can be simple and specific. So an alternate approach would be to standardize what build configuration looks like across projects, rather than overloading hxml.

So my alternative suggestion is to *standardize a subset of OpenFL's project.xml/include.xml functionality*, because that project has already solved this problem in an elegant way. (Syntax and format are less important than functionality here, pick your favorite markup language. I'll use YAML for this example because it's concise.)

There has [also been a suggestion to add more metadata fields to haxelib.json](https://github.com/HaxeFoundation/haxe-evolution/issues/34), and include.xml solves that problem as well. If haxelib.yaml (or whatever) is present, it takes precedence over haxelib.json, and otherwise can include the same information. And while we're at it this also eliminates the need for extraParams.hxml.

```yaml
name: hxpk
version: "0.1.0"
license: "MIT"
contributors: ["bendmorris"]

src: ["src"]

flags:
- "-dce=full"

dependencies:
- format
- hxbit

section:
- if: test
  unless: no-test
  flags: ["-debug"]
  dependencies: ["unit"]
  src: ["src-tests"]
```

This generates a set of compiler args: `haxe -cp src -dce=full -lib format -lib hxbit`. If called with -Dtest, it adds extra args: `-debug -lib unit -cp src-tests`.

There might be pushback that "haxe/haxelib is not a build tool." True, but having so much fragmentation among build tools is not great and Haxe doesn't have a clear winner in that space. At minimum we should have a standard format and set of semantics that works for basic projects and is expressive/extensible enough for build tools to consume without needing to provide their own entirely separate format.
